dbt_poc:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: '12345678'
      dbname: postgres
      schema: public
    prod:
      type: mysql
      server: localhost
      port: 3306  # optional
      database: test_poc
      schema: test_poc
      username: root
      password: '12345678' # las claves deben estar entre comillas
      driver: MySQL ODBC 8.0 ANSI Driver