dbt_poc:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: host.docker.internal
      port: 5432
      user: admin
      pass: '12345678'
      dbname: spark
      schema: public